### PR TITLE
Add environment variables for --config and terminal size check args

### PR DESCRIPTION
**Pull request by tangowithfoxtrot**
This simply adds the ability to use environment variables for the existing `--config` and `--disable-terminal-size-checks` args:

```sh
MANAGARR_DISABLE_TERMINAL_SIZE_CHECKS=true
MANAGARR_CONFIG_FILE=~/.config/managarr/config.yml
managarr
```

Currently, I have to use an alias to accomplish this: `alias managarr='managarr --config ~/.config/managarr/config.yml --disable-terminal-size-checks'`. Having the ability to configure this behavior via environment variables would make this easier.

### CODE REVIEW

**Comment by Dark-Alex-17** [comment]
This looks fine to me! I also just created an [RC for v0.1.6](https://github.com/Dark-Alex-17/managarr/tree/rc/v0.1.6-address-community-comments) to address #8 , so would you mind re-pointing this branch to the rc/v0.1.6 branch? I'll merge it in after that and kick off a new release.

**Review by Dark-Alex-17 — APPROVED** [review]
Thank you for being flexible!

**Comment by tangowithfoxtrot** [comment]
I _think_ I've got it pointed at the desired branch now. Lmk if I did that wrong 😅

**Comment by Dark-Alex-17** [comment]
Nah you got it right! 😛

**Pull request merged**
